package com.example

const val MAX_VALUE: Int = 7

val BOOL = "bool"
val INT = "int"
val INT_POINTER = "$INT*"
val FLOAT = "float"
val UNSIGNED_INT = "unsigned int"
//val UNSIGNED_INT = "int"
val VOID = "void"
val MAIN = "main"
val ARITHMETIC_OPERATIONS: List<String> = listOf("+", "-", "*", "/")
val ADDITION = "+"
val SUBTRACTION = "-"
val MOD = "%"
val DIV = "/"
val MULTIPLICATION = "*"
val LOGICAL_NEGATION = "!"
val LOGICAL_AND = "&&"
val LOGICAL_OR = "||"
val RELATIONAL_OPERATIONS: List<String> = listOf("<", ">", "<=", ">=", "==", "!=")
val LESS_THAN = "<"
val LESS_EQUAL_THAN = "<="
val MORE_THAN = ">"
val MORE_EQUAL_THAN = ">="
val INCREMENT = "++"
val DECREMENT = "--"
val BITWISE_OPERATIONS: List<String> = listOf("<<", ">>", "|", "&")
val IDENTIFIER: List<String> = listOf("a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z")
val CARRIAGE_RETURN = "\n"
val PRINT_CARRIAGE_RETURN = "\\n"
val EQUALLY = "="
val COMMA = ","
val DOT = "."
val DASH = "-"
val UNDERSCORE = "_"
val SEMICOLON = ";"
val COLON = ":"
val QUOTES = "\""
val AMPERSAND = "&"
val END_OF_LINE = "$SEMICOLON$CARRIAGE_RETURN"
//val LIBRARY: List<String> = listOf("java.util.*;")
val LIBRARY: List<String> = listOf("stdio.h", "stdbool.h")
//val INCLUDE: List<String> = listOf("import ")
val INCLUDE: List<String> = listOf("#include <", ">")
val ROUND_BRACKET = "("
val ROUND_BRACKET_ = ")"
val BRACE = "{"
val BRACE_ = "}"
val SQUARE_BRACKET = "["
val SQUARE_BRACKET_ = "]"
val BREAK = "break"
val CONTINUE = "continue"
val RETURN = "return"
val PRINTF = "printf"
val IF = "if"
val ELSE = "else"
val SWITCH = "switch"
val CASE = "case"
val DEFAULT = "default"
val WHILE = "while"
val DO = "do"
val FOR = "for"
val ARITHMETIC_CONVERSION = "arithmeticConversion"